### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [Nurou/inkhouse-uk#1]
# Katselmointi

Terve @Nurou! Tässä lyhyt katselmointi Full Stack kurssin projektistasi.

### Mitä tein?

Selasin kaikki sivut läpi.

### Kokemus

- Selkeä ja tyylikäs sivusto, hyvää työtä! 🏆
- Kuvien latauksenaikaikaiset placeholderit parantaa huomattavasti käyttökokemusta
- Skaalautuu hyvin myös pienemillä näytöille
- Sivut latautuvat todella nopeasti
- Suurempia [saavutettavuus](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML) ongelmiakaan löytynyt. Etusivun referenssilogoissa, kuten kaikissa muissakin kuvissa, voisi käyttää [alt-tekstejä](https://webaim.org/techniques/alttext/#basics), kuten "University of London", niin näytönlukijat pystyvät tulkitsemaan ne. Myös otsikoiden hierarkiaan (h1, h2, ...) kannattaa kiinnittää huomiota, koska usein näytönlukioilla luetaan ensin h1-tason otsikot, josta siirrytään hierarkiassa alaspäin. Tämän osalta ei kyllä suurempia ongelmia ollut

## Koodi

- Koodi on kaikin puolin selkeästi organisoitua, hyvä!
- Gatsby on todella hyvä valinta tähän käyttötarkoitukseen
- Olet selvästi sisäistänyt erittäin hyvin komponenttipohjaisen ajattelun, kun olet toteuttanut paljon uudelleenkäytettäviä pieniä ja selkeitä komponentteja
- Todella mainiota teema-konfiguraation ja CSS-in-JS käyttöä. Suosittelen tutustumaan nk. [styled system](https://styled-system.com/)-malliin, jos ei ole vielä tuttu 
- Tämä tiedosto on aika oudossa paikassa: https://github.com/Nurou/inkhouse-uk/blob/master/src/Hooks/InkHouse_Light-Gray_Horizontal-300x142.png
- Tämä tuskin on tarpeen: https://github.com/Nurou/inkhouse-uk/blob/master/src/Hooks/use-modal.js#L15

## Kokonaisuus

- Todella selkeä ja tyylikäs sivusto, jossa ei sivujen latautumista tarvitse paljoa odotella
- Koodi on erittäin hyvin organisoitua ja laadultaan timanttista

**Comment by Nurou** [comment]
Terve Kalle,

Suuret kiitokset projektin läpikäynnistä, kannustavasta palautteesta ja parannusvinkkeistä 😊Projekti on vielä työn alla ja pidän kaiken tämän mielessä. 

Ja styled components (& rebass) kyllä tuli tutuksi projektin aikana - täytyy ehdottomasti kokeilla sitä jatkossa. 

Kiitos!
